# Generated by Django 3.0.8 on 2020-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_school_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_admin',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Account Verifed'),
        ),
    ]
