# Generated by Django 3.0.8 on 2020-07-26 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Children', '0002_childern_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parentAuth', to=settings.AUTH_USER_MODEL, verbose_name="Parent's Auth"),
            preserve_default=False,
        ),
    ]
