# Generated by Django 3.0.8 on 2020-07-27 14:41

import Children.validators
import Transport.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20200727_2011'),
        ('Children', '0003_parent_auth'),
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint1', models.CharField(help_text='One end of route', max_length=120, verbose_name='Endpoint1')),
                ('endpoint1_lat', models.CharField(max_length=120, null=True, verbose_name='Endpoint1 Location(Latitude)')),
                ('endpoint1_long', models.CharField(max_length=120, null=True, verbose_name='Endpoint1 Location(Longitude)')),
                ('endpoint2', models.CharField(help_text='Another end of route', max_length=120, verbose_name='Endpoint2')),
                ('endpoint2_lat', models.CharField(max_length=120, null=True, verbose_name='Endpoint2 Location(Latitude)')),
                ('endpoint2_long', models.CharField(max_length=120, null=True, verbose_name='Endpoint2 Location(Longitude)')),
                ('via', models.TextField(blank=True, default='', help_text="This contain the comma separetes values like ' test1,test2,test3, ..'", verbose_name='Via Area')),
                ('country', models.CharField(max_length=120, verbose_name='County')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
            },
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.FileField(blank=True, null=True, upload_to=Transport.models.uploadLogFile, verbose_name='Log File')),
            ],
            options={
                'verbose_name': 'Travel History',
                'verbose_name_plural': 'Travel Historys',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('no', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Vehicle No')),
                ('no_of_seat', models.IntegerField(default=0, help_text='No of students travel in That Bus', verbose_name='Seats')),
                ('country', models.CharField(max_length=120, verbose_name='County')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('route_no', models.ForeignKey(help_text='Bus Route Nuber', on_delete=django.db.models.deletion.CASCADE, related_name='vehicleBusRoute', to='Transport.BusRoute', verbose_name='Route No')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='TravelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.CharField(max_length=120, verbose_name='Pickup Latitude')),
                ('pickup_long', models.CharField(max_length=120, verbose_name='Pickup Longitude')),
                ('pickup_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Pickup Date Time')),
                ('pickup_notified', models.BooleanField(default=False, help_text='To concern Parent of child', verbose_name='Pickup Notified')),
                ('drop_lat', models.CharField(max_length=120, verbose_name='Drop Latitude')),
                ('drop_long', models.CharField(max_length=120, verbose_name='Drop Longitude')),
                ('drop_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Drop Date Time')),
                ('drop_notification', models.BooleanField(default=False, help_text='To concern Parent of child', verbose_name='Drop Notified')),
                ('parent_phone', models.CharField(help_text="Parent's phone number of concern Child", max_length=10, validators=[Children.validators.phoneVerify], verbose_name='Parent Phone')),
                ('parent_email', models.EmailField(help_text="Employee's Email", max_length=254, unique=True, verbose_name='Email')),
                ('children', models.ForeignKey(help_text='Children Account Linked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrenTravelLog', to='Children.Childern', verbose_name='Children')),
                ('travel_history', models.ForeignKey(help_text='Travel History', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travelHistoryTravelLog', to='Transport.TravelHistory', verbose_name='Travel History')),
            ],
            options={
                'verbose_name': 'Travel Log',
                'verbose_name_plural': 'Travel Logs',
            },
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='children',
            field=models.ManyToManyField(related_name='travelHistory', through='Transport.TravelLog', to='Children.Childern', verbose_name='Childrens'),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelHistorySchool', to='School.School', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelHistoryVehicle', to='Transport.Vehicle', verbose_name='Vehicle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employeeVehicle', to='Transport.Vehicle', verbose_name="Employee's Vehicle"),
            preserve_default=False,
        ),
    ]
